### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by hkrist** [BME-MIT-IET/IET-team-one-iet-2018#1]
We should integrate the project with Travis CI to see build outputs on the fly.

**Comment by hkrist** [comment]
#f052fa2800dad4b0980e8d4098feb3fd08c08740

**Comment by hkrist** [comment]
f052fa2800dad4b0980e8d4098feb3fd08c08740

**Comment by sidun** [comment]
The .gradlew file needs exec permissions, fixed here: 9c19d5c12333f9131c96733ee513911325e0b658

**Comment by hkrist** [comment]
Added a build status flag to the README.md file here: fb9ef2fedfe824532dfab7102c3e35be03874a99

**Comment by hkrist** [comment]
We should add a .gitignore file for Android Studio IDE utility dirs and files.

**Comment by sidun** [comment]
Added the Intellij specific .idea folder to the .gitignore. Also ignoring the .iml files. Changeset here: 48194284e8e12735dd38b4d01a6ae5e6a3dd5f89

The automated build is still failing though. We might need to add a keystore. @bancsdan ?

**Comment by hkrist** [comment]
Cool! In the meantime I added the fancy Travis Build status flag for the project fb9ef2fedfe824532dfab7102c3e35be03874a99 .

**Comment by bancsdan** [comment]
Tried running the Travis build in debug mode, but it would require communication with the Travis team, so we decided against it.
"This feature is available for private repositories and those public repositories for which the feature is enabled. To have the feature enabled for a public repository, please email us at support@travis-ci.com indicating which ones. Push access to the repository is also required."

**Comment by hkrist** [comment]
I started to follow the guides here https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4. The article has some mistakes which I have to fix manually, but work in progress: 
b8141ddf7b60f7d19e51943b856034e18450b25e , a2a34e5de8348b6f5e28f09d21641f04f1cc5c46

**Comment by sidun** [comment]
Did some search, try to use ARM ABI for API-24 to fix the build.

**Comment by hkrist** [comment]
Thanks! On it 74ba6a148b2636e25e20b92cb6847b777bc70cbc.

**Comment by sidun** [comment]
The API 24 config will probably not work as the project's API is set to 25 so I created a new branch where I can test the API 25 travis config. I still have some issues with signing the apk in that branch though.

**Comment by sidun** [comment]
Travis builds now pass on the branch [api25build](https://github.com/BME-MIT-IET/IET-team-one-iet-2018/tree/api25build). This is only a build process, emulation is not working yet. Pull request has been sent.

**Comment by Berzegeri** [comment]
Nice job Guys!
