### ISSUE TITLE
Unit testing categories

### ISSUE THREAD

**Issue by bancsdan** [BME-MIT-IET/IET-team-one-iet-2018#13]

**Comment by bancsdan** [comment]
Started creating unit tests for Categories, along the way I realised there are few functions that can be unit tested, but that is not the problem. Because of external dependencies i started using Mockito, added it to the build configuration.

**Comment by bancsdan** [comment]
Had trouble testing certain methods because of external dependencies related to static classes which can not be mocked with Mockito, excluded these tests.

**Comment by bancsdan** [comment]
There are several hard to test cases, for example: can not test ExpenseFirebaseSource::getExpense(...) because there are too many dependencies too deep in the code.

**Comment by hkrist** [comment]
Same with my tests, maybe focus on more backend related units.

**Comment by bancsdan** [comment]
Managed to find a testable module, it is a utility class for handling dates. Committed to unittest branch.

**Comment by hkrist** [comment]
Seems fine. Closing this.
