### ISSUE TITLE
Main activity tests

### ISSUE THREAD

**Issue by hkrist** [BME-MIT-IET/IET-team-one-iet-2018#14]
Create unit tests for the main activity, which helps the user post and edit their expenses in different categories.

**Comment by hkrist** [comment]
It doesn't seem to be anything to test, since its all view logic. 2 hours of search and trial and error didn't yield any success.

**Comment by hkrist** [comment]
There are some backend logic in app.outlay.domain.model, I am working on those.

**Comment by hkrist** [comment]
I added some skeletons to the unit tests which I will work on later on: 7260704138c2a1eeaeac7a8f0fa023f6c5721df2

**Comment by hkrist** [comment]
The PR got merged, can we close this issue?

**Comment by bancsdan** [comment]
Seems good!
