### ISSUE TITLE
Slack integration for the project

### ISSUE THREAD

**Issue by hkrist** [BME-MIT-IET/IET-team-one-iet-2018#2]
It's nice to have a channel on our Slack Workspace where we can get notified about events happening on the repo. We should integrate it with this github project to see the logs.

**Comment by sidun** [comment]
Agreed. I installed a webhook onto the slack workspace. It will only notify about commit events for now, but other events can be added/removed at anytime.

**Comment by hkrist** [comment]
It works! $$$$

**Comment by hkrist** [comment]
<img width="535" alt="screen shot 2018-04-30 at 20 06 14" src="https://user-images.githubusercontent.com/10967097/39442593-127ca6dc-4cb2-11e8-9f95-e816ef295a9a.png">
