### ISSUE TITLE
Running static analitics with SonarQube

### ISSUE THREAD

**Issue by Berzegeri** [BME-MIT-IET/IET-team-one-iet-2018#3]
We use SonarCube to detect bugs, code smells and security vulnerabilities.

**Comment by hkrist** [comment]
I found this site https://sonarcloud.io. Maybe we could use this to host the platform?

**Comment by Berzegeri** [comment]
Nice, this could work!

**Comment by hkrist** [comment]
We should also fix some bugs that we found, before closing this issue!

**Comment by Berzegeri** [comment]
OK! I'll fix these ones.
![kep](https://user-images.githubusercontent.com/18070480/39473844-2f44b36e-4d51-11e8-8a5c-1ef1156858ab.png)

**Comment by Berzegeri** [comment]
Had some problems with these, I'm moving on to Vulnerabilities...

**Comment by Berzegeri** [comment]
I sent a pull request, and committed the sonar integration in the travis.yml
@hkrist Could you check please?

**Comment by hkrist** [comment]
It got merged +1
